// This file is generated by Misaki Studio. Do not edit.

/**
 * One row of cms/sample, as the exported views return it.
 *
 * `id` is the row's own id and is always present. Every column is OPTIONAL:
 * a cell that was never filled in has no value at all, and a view may
 * project only some columns, so nothing here can be promised.
 *
 * Secret columns are absent by construction — the evaluator drops them
 * from the model before it projects anything.
 */
export type SampleRow = {
  id: string;
  Title?: string;
  Body?: string;
  Published?: string;
};

/**
 * The rows the PUBLIC views of this table return.
 *
 * ⚠️ A RESTRICTED view's rows are NOT here, and that is deliberate:
 * anything in this bundle has already reached the browser, so shipping
 * them and hiding them would be a leak with extra steps. They are served
 * by the generated backend instead.
 */
const rows: SampleRow[] = [
  {
    id: "4928a76a-1cdb-4557-ae10-75f95eb6aafa",
    Title: "Welcome to your CMS",
    Body: "Edit these rows in the DATA tab, then place them on a page.",
    Published: "true",
  },
  {
    id: "3d67f3e2-e416-4435-ad3c-16f4fa9646f9",
    Title: "Reading content on a page",
    Body: "Mount the Published view on a page, then repeat a node over views.<name>.",
    Published: "true",
  },
  {
    id: "41507746-ab54-446f-96cc-2f532c8eea9d",
    Title: "A draft, so you can see filtering",
    Body: "This row is not published — a good first thing to filter on.",
    Published: "false",
  },
];

/**
 * View "Published" — public, no parameters, so its answer is fully
 * known at export time and is baked rather than computed.
 *
 * Returns: Id, Title, Body, Published
 */
export const Published = (): SampleRow[] =>
  [
    "4928a76a-1cdb-4557-ae10-75f95eb6aafa",
    "3d67f3e2-e416-4435-ad3c-16f4fa9646f9",
    "41507746-ab54-446f-96cc-2f532c8eea9d",
  ]
    .map((id) => rows.find((row) => row.id === id))
    .filter((row): row is SampleRow => !!row);
