// This file is generated by Misaki Studio. Do not edit.
"use client";
import * as react from "react";
import * as msi from "misaki-studio-internal";
import { SVGs } from "../design-system/images";
import styles from "./index.module.scss";

export default ({
  className = "",
  style,
  divProps,
}: {
  className?: string;
  style?: React.CSSProperties;
  divProps?: msi.DivProps;
}) => {
  const id = msi.utils.getCount();
  const rootElement = react.useRef<HTMLDivElement>(null);
  return (
    <div
      {...divProps}
      style={{ ...style }}
      className={`${className} misaki-project-content  ${id} ${styles["E14ydix"]}`}
      ref={(element) => {
        (rootElement as any).current = element;
        divProps?.ref?.(element);
      }}
    >
      <div className={` ${id} ${styles["Ek1sc9k"]}`}>
        <div className={` ${id} ${styles["Eykduw4"]}`}>
          <span className={` ${id} ${styles["Ea6tl43"]}`}>{"nexus"}</span>
        </div>
        <div className={` ${id} ${styles["E72kl4h"]}`} />
        <div className={` ${id} ${styles["Eoedk8y"]}`}>
          <span className={` ${id} ${styles["E00tagx"]}`}>{"Home"}</span>
        </div>
        <div className={` ${id} ${styles["E244tm1"]}`}>
          <span className={` ${id} ${styles["Edqkju0"]}`}>{"Schedule"}</span>
        </div>
        <div className={` ${id} ${styles["Estyx1q"]}`}>
          <span className={` ${id} ${styles["E5falal"]}`}>{"Speakers"}</span>
        </div>
        <div className={` ${id} ${styles["Ei2tiyx"]}`}>
          <span className={` ${id} ${styles["Etp996w"]}`}>{"Tickets"}</span>
        </div>
        <div className={` ${id} ${styles["E9rjkfi"]}`}>
          <span className={` ${id} ${styles["Eldzanh"]}`}>{"Venue"}</span>
        </div>
        <div className={` ${id} ${styles["E3e3mjt"]}`}>
          <span className={` ${id} ${styles["Ef0jcrs"]}`}>{"Sponsors"}</span>
        </div>
      </div>
      <div className={` ${id} ${styles["Emigl3v"]}`}>
        <div className={` ${id} ${styles["Em0185v"]}`}>
          {SVGs.types.landing.hero_b1("none")}
        </div>
        <div className={` ${id} ${styles["Eb9s4v8"]}`}>
          <span className={` ${id} ${styles["Emw7v37"]}`}>
            {"OCTOBER 15-17, 2052"}
          </span>
        </div>
        <div className={` ${id} ${styles["E9rliis"]}`}>
          <span className={` ${id} ${styles["Ele18qr"]}`}>
            {"Horizon Convention Center, TechCity, Utopolis"}
          </span>
        </div>
        <div className={` ${id} ${styles["Ek89f1l"]}`}>
          <span className={` ${id} ${styles["Evup59k"]}`}>
            {"NEXT-GEN AI SUMMIT"}
          </span>
        </div>
        <div className={` ${id} ${styles["Eps91o5"]}`}>
          <span className={` ${id} ${styles["E2dkpx0"]}`}>
            {
              "Explore the cutting-edge innovations shaping the future of artificial intelligence.\nJoin global leaders and visionaries for two days of insights, discussions, and breakthroughs."
            }
          </span>
        </div>
        <div className={` ${id} ${styles["Edlhx11"]}`}>
          <div className={` ${id} ${styles["E0o6xr8"]}`}>
            <span className={` ${id} ${styles["Ecamnz7"]}`}>
              {"Early bird tickets"}
            </span>
          </div>
          <div className={` ${id} ${styles["E7r6onx"]}`}>
            {SVGs.types.landing.arrow_white("meet")}
          </div>
        </div>
      </div>
      <div className={` ${id} ${styles["Eptdfej"]}`}>
        <div className={` ${id} ${styles["Encav17"]}`}>
          {SVGs.types.landing.logo_1("meet")}
        </div>
        <div className={` ${id} ${styles["Elmw460"]}`}>
          {SVGs.types.landing.logo_2("meet")}
        </div>
        <div className={` ${id} ${styles["Erq3pn5"]}`}>
          {SVGs.types.landing.logo_3("meet")}
        </div>
        <div className={` ${id} ${styles["Ehcvah8"]}`}>
          {SVGs.types.landing.logo_4("meet")}
        </div>
        <div className={` ${id} ${styles["E0okzti"]}`}>
          {SVGs.types.landing.logo_5("meet")}
        </div>
      </div>
      <div className={` ${id} ${styles["E7vlaxd"]}`}>
        <div className={` ${id} ${styles["Eak4fwa"]}`}>
          <span className={` ${id} ${styles["Em6k649"]}`}>{"Speakers"}</span>
        </div>
        <div className={` ${id} ${styles["Ehgu2ek"]}`}>
          {SVGs.types.landing.speakers_group("meet")}
        </div>
        <div className={` ${id} ${styles["Ed8d1cg"]}`}>
          <span className={` ${id} ${styles["Eousrkf"]}`}>
            {
              "Hear from global AI leaders, researchers, and entrepreneurs who are defining the future of artificial intelligence."
            }
          </span>
        </div>
        <div className={` ${id} ${styles["E6pj6h0"]}`} />
        <div className={` ${id} ${styles["Eho03he"]}`} />
        <div className={` ${id} ${styles["E7xj5mb"]}`} />
        <div className={` ${id} ${styles["Ew61r92"]}`} />
        <div className={` ${id} ${styles["Eji7csp"]}`}>
          <div className={` ${id} ${styles["El4fnop"]}`}>
            <span className={` ${id} ${styles["Ewqvdwo"]}`}>{"And more"}</span>
          </div>
          <div className={` ${id} ${styles["Ej4q87x"]}`}>
            {SVGs.types.landing.arrow_white("meet")}
          </div>
        </div>
      </div>
      <div className={` ${id} ${styles["E8ypxkr"]}`}>
        <div className={` ${id} ${styles["Eb0hl8u"]}`}>
          <span className={` ${id} ${styles["Emmxbgt"]}`}>
            {"Technologies"}
          </span>
        </div>
        <div className={` ${id} ${styles["Evcvqsu"]}`}>
          <span className={` ${id} ${styles["E7y7f1p"]}`}>
            {
              "Explore advanced machine learning, natural language processing, AI-driven automation, and emerging cybersecurity applications."
            }
          </span>
        </div>
      </div>
      <div className={` ${id} ${styles["E8vgkzc"]}`}>
        <div className={` ${id} ${styles["Ev7nkey"]}`}>
          <span className={` ${id} ${styles["E7sz8nt"]}`}>
            {"Networking Opportunities"}
          </span>
        </div>
        <div className={` ${id} ${styles["Eltr5m8"]}`}>
          <span className={` ${id} ${styles["Exg6vu7"]}`}>
            {
              "Enjoy exclusive networking sessions, roundtables, and social events to foster collaboration and spark new partnerships."
            }
          </span>
        </div>
      </div>
      <div className={` ${id} ${styles["Eqobzwd"]}`}>
        <div className={` ${id} ${styles["Euky17e"]}`}>
          <span className={` ${id} ${styles["E67drfd"]}`}>{"AGENDA"}</span>
        </div>
        <div className={` ${id} ${styles["Ewcf09w"]}`}>
          <span className={` ${id} ${styles["E8xqoir"]}`}>
            {"October 15-17, 2052 | Horizon Convention Center, Amsterdam"}
          </span>
        </div>
        <div className={` ${id} ${styles["Ehjrf0a"]}`}>
          {SVGs.types.landing.agenda_frame("none")}
        </div>
        <div className={` ${id} ${styles["Eaq20tn"]}`}>
          <span className={` ${id} ${styles["Emchr1m"]}`}>{"Day 1"}</span>
        </div>
        <div className={` ${id} ${styles["E8tcvd9"]}`}>
          <span className={` ${id} ${styles["Ekfsll8"]}`}>
            {"09:00 – 19:00"}
          </span>
        </div>
        <div className={` ${id} ${styles["Ei6conk"]}`}>
          <span className={` ${id} ${styles["Etssevj"]}`}>
            {"AI Innovations & Trends"}
          </span>
        </div>
        <div className={` ${id} ${styles["Env1r0r"]}`}>
          <span className={` ${id} ${styles["Ezhhh8q"]}`}>
            {
              "The summit kicks off with a keynote, expert panels, and discussions on AI’s impact, ethics, and automation. Hands-on workshops and a networking event wrap up the day."
            }
          </span>
        </div>
        <div className={` ${id} ${styles["Ebf9alg"]}`}>
          <span className={` ${id} ${styles["En1p0tf"]}`}>{"Day 2"}</span>
        </div>
        <div className={` ${id} ${styles["Es2920e"]}`}>
          <span className={` ${id} ${styles["E4nkq99"]}`}>
            {"09:00 – 20:00"}
          </span>
        </div>
        <div className={` ${id} ${styles["Ejvb7tt"]}`}>
          <span className={` ${id} ${styles["Evhqy1s"]}`}>
            {"AI Technologies & Applications"}
          </span>
        </div>
        <div className={` ${id} ${styles["Ehg7h8y"]}`}>
          <span className={` ${id} ${styles["Et2n7gx"]}`}>
            {
              "Explore the latest in generative AI, robotics, and NLP, with industry-led discussions and tech demos. A startup showcase and investor insights highlight AI’s business potential."
            }
          </span>
        </div>
        <div className={` ${id} ${styles["Eibu28l"]}`}>
          <span className={` ${id} ${styles["Ety9sgk"]}`}>{"Day 3"}</span>
        </div>
        <div className={` ${id} ${styles["E99q0pt"]}`}>
          <span className={` ${id} ${styles["Ekw5qxs"]}`}>
            {"09:30 – 16:00"}
          </span>
        </div>
        <div className={` ${id} ${styles["Eiuys70"]}`}>
          <span className={` ${id} ${styles["Euheiez"]}`}>
            {"Future of AI & Networking"}
          </span>
        </div>
        <div className={` ${id} ${styles["El7kup5"]}`}>
          <span className={` ${id} ${styles["Ewu0kx4"]}`}>
            {
              "Dive into AI’s long-term impact, attend expert-led workshops, and watch the startup pitch competition. The event closes with a visionary keynote and final networking sessions."
            }
          </span>
        </div>
        <div className={` ${id} ${styles["Eq2r9m6"]}`}>
          <div className={` ${id} ${styles["Eyjuzhg"]}`}>
            <span className={` ${id} ${styles["Ea6appf"]}`}>
              {"View detailed schedule"}
            </span>
          </div>
          <div className={` ${id} ${styles["Eascn7t"]}`}>
            {SVGs.types.landing.arrow_white("meet")}
          </div>
        </div>
      </div>
      <div className={` ${id} ${styles["Exmhkr5"]}`}>
        <div className={` ${id} ${styles["Eoogwzc"]}`}>
          <span className={` ${id} ${styles["E19sl87"]}`}>
            {"KEYNOTE SPEAKERS"}
          </span>
        </div>
        <div className={` ${id} ${styles["Es87vp9"]}`}>
          <span className={` ${id} ${styles["E3unlx8"]}`}>
            {"Meet the industry leaders shaping the future of AI."}
          </span>
        </div>
        <div className={` ${id} ${styles["Esc4bfk"]}`}>
          <div className={` ${id} ${styles["Ebopjqh"]}`}>
            <span className={` ${id} ${styles["Enb59yg"]}`}>
              {"Dr. Emily Carter"}
            </span>
          </div>
          <div className={` ${id} ${styles["Ebxzwgj"]}`}>
            <span className={` ${id} ${styles["Enkfmoi"]}`}>
              {"Chief AI Scientist, OpenAI"}
            </span>
          </div>
        </div>
        <div className={` ${id} ${styles["Eebohyz"]}`} />
        <div className={` ${id} ${styles["Exx8kjm"]}`}>
          <div className={` ${id} ${styles["Eklk0pa"]}`}>
            <span className={` ${id} ${styles["Ew7zqx9"]}`}>{"Elon Park"}</span>
          </div>
          <div className={` ${id} ${styles["Ekuudfc"]}`}>
            <span className={` ${id} ${styles["Ewha3nb"]}`}>
              {"CTO, DeepMind"}
            </span>
          </div>
        </div>
        <div className={` ${id} ${styles["En8iyxs"]}`} />
        <div className={` ${id} ${styles["Ech8308"]}`} />
        <div className={` ${id} ${styles["E6p0mz0"]}`}>
          <div className={` ${id} ${styles["Erfqioj"]}`}>
            <span className={` ${id} ${styles["E4126xe"]}`}>{"Laura Kim"}</span>
          </div>
          <div className={` ${id} ${styles["Eyf2tj8"]}`}>
            <span className={` ${id} ${styles["Eb0ehs3"]}`}>
              {"AI Policy Advisor, EU Commission"}
            </span>
          </div>
        </div>
        <div className={` ${id} ${styles["E2eeude"]}`} />
        <div className={` ${id} ${styles["Ed0c22b"]}`}>
          <div className={` ${id} ${styles["Ewg5q0l"]}`}>
            <span className={` ${id} ${styles["E82lg8k"]}`}>
              {"Dr. Alan Foster"}
            </span>
          </div>
          <div className={` ${id} ${styles["Elhkfhu"]}`}>
            <span className={` ${id} ${styles["Ex405pt"]}`}>
              {"Stanford AI Lab"}
            </span>
          </div>
        </div>
        <div className={` ${id} ${styles["Ev4gnhv"]}`}>
          <div className={` ${id} ${styles["Eb30lwf"]}`}>
            <span className={` ${id} ${styles["Empgc4e"]}`}>{"And more"}</span>
          </div>
          <div className={` ${id} ${styles["Ekivgdv"]}`}>
            {SVGs.types.landing.arrow_white("meet")}
          </div>
        </div>
      </div>
      <div className={` ${id} ${styles["Elsu9bn"]}`}>
        <div className={` ${id} ${styles["E0g9u32"]}`}>
          <span className={` ${id} ${styles["Ec2pkb1"]}`}>{"WHY ATTEND?"}</span>
        </div>
        <div className={` ${id} ${styles["Eckfm7p"]}`}>
          <span className={` ${id} ${styles["Eo6vcfo"]}`}>
            {
              "Discover why Next-Gen AI Summit is the must-attend event for AI professionals, innovators, and industry leaders."
            }
          </span>
        </div>
        <div className={` ${id} ${styles["E6kqguu"]}`}>
          <div className={` ${id} ${styles["Ero02bo"]}`}>
            <span className={` ${id} ${styles["E49bqkj"]}`}>{"01"}</span>
          </div>
          <div className={` ${id} ${styles["Ew31d6r"]}`}>
            <span className={` ${id} ${styles["E7ph3eq"]}`}>
              {"CUTTING-EDGE INSIGHTS"}
            </span>
          </div>
          <div className={` ${id} ${styles["Ev2iunp"]}`}>
            <span className={` ${id} ${styles["E6oykvo"]}`}>
              {
                "Gain firsthand knowledge from top AI experts and pioneers shaping the industry."
              }
            </span>
          </div>
        </div>
        <div className={` ${id} ${styles["Eiuoswj"]}`}>
          <div className={` ${id} ${styles["Ex7yqqd"]}`}>
            <span className={` ${id} ${styles["E8uegyc"]}`}>{"02"}</span>
          </div>
          <div className={` ${id} ${styles["E3ze4xk"]}`}>
            <span className={` ${id} ${styles["Efltv5j"]}`}>
              {"HANDS-ON LEARNING"}
            </span>
          </div>
          <div className={` ${id} ${styles["E6a1e32"]}`}>
            <span className={` ${id} ${styles["Ehwh4b1"]}`}>
              {
                "Participate in interactive workshops, live demos, and deep-dive sessions to sharpen your skills."
              }
            </span>
          </div>
        </div>
        <div className={` ${id} ${styles["Erq8qmk"]}`}>
          <div className={` ${id} ${styles["Ek6tkwq"]}`}>
            <span className={` ${id} ${styles["Evt9b4p"]}`}>{"03"}</span>
          </div>
          <div className={` ${id} ${styles["Edfwig9"]}`}>
            <span className={` ${id} ${styles["Ep2c8o8"]}`}>
              {"EXCLUSIVE NETWORKING"}
            </span>
          </div>
          <div className={` ${id} ${styles["Ef1ohz1"]}`}>
            <span className={` ${id} ${styles["Eqo4870"]}`}>
              {
                "Connect with AI leaders, investors, startups, and fellow professionals at curated networking events."
              }
            </span>
          </div>
        </div>
        <div className={` ${id} ${styles["E9qum8w"]}`}>
          <div className={` ${id} ${styles["Etex8e2"]}`}>
            <span className={` ${id} ${styles["E608wmx"]}`}>{"04"}</span>
          </div>
          <div className={` ${id} ${styles["E9ddqf8"]}`}>
            <span className={` ${id} ${styles["Ekztgn7"]}`}>
              {"INNOVATION SHOWCASE"}
            </span>
          </div>
          <div className={` ${id} ${styles["Egtoe95"]}`}>
            <span className={` ${id} ${styles["Esg44h4"]}`}>
              {
                "Explore groundbreaking AI solutions, from emerging startups to tech giants redefining the future."
              }
            </span>
          </div>
        </div>
      </div>
      <div className={` ${id} ${styles["E580sx3"]}`}>
        <div className={` ${id} ${styles["Ea9cbzs"]}`}>
          <span className={` ${id} ${styles["Elvs27r"]}`}>
            {"What Past Attendees Say"}
          </span>
        </div>
        <div className={` ${id} ${styles["E3peqp8"]}`}>
          <div className={` ${id} ${styles["E4r5y8j"]}`}>
            {SVGs.types.landing.nav_arrow_left("meet")}
          </div>
        </div>
        <div className={` ${id} ${styles["Ealzicd"]}`}>
          <div className={` ${id} ${styles["E21kw1d"]}`}>
            {SVGs.types.landing.nav_arrow_right("meet")}
          </div>
        </div>
        <div className={` ${id} ${styles["Egk1sua"]}`}>
          <div className={` ${id} ${styles["Emm1s4p"]}`}>
            <span className={` ${id} ${styles["Ey8hico"]}`}>
              {"GAME-CHANGING INSIGHTS"}
            </span>
          </div>
          <div className={` ${id} ${styles["Edp33m1"]}`}>
            <span className={` ${id} ${styles["Epbitu0"]}`}>
              {
                '"This summit opened my eyes to the future of AI and how it will shape industries."'
              }
            </span>
          </div>
          <div className={` ${id} ${styles["E92ziz7"]}`} />
          <div className={` ${id} ${styles["Ezg8k43"]}`}>
            <span className={` ${id} ${styles["Eb2oac2"]}`}>
              {"Mark Vandenberg"}
            </span>
          </div>
          <div className={` ${id} ${styles["Ezk7c1f"]}`}>
            <span className={` ${id} ${styles["Eb6n29e"]}`}>
              {"CTO, NeuralTech"}
            </span>
          </div>
          <div className={` ${id} ${styles["Erctt8b"]}`} />
        </div>
        <div className={` ${id} ${styles["Errtjgs"]}`}>
          <div className={` ${id} ${styles["Er2377m"]}`}>
            <span className={` ${id} ${styles["E2oixfl"]}`}>
              {"THE BEST AI EVENT!"}
            </span>
          </div>
          <div className={` ${id} ${styles["Eqa3jiw"]}`}>
            <span className={` ${id} ${styles["E1wj9qv"]}`}>
              {
                '"Incredible speakers, top-tier networking, and cutting-edge discussions all in one place."'
              }
            </span>
          </div>
          <div className={` ${id} ${styles["Exhw0y2"]}`} />
          <div className={` ${id} ${styles["Ekz9wjv"]}`}>
            <span className={` ${id} ${styles["Ewlpmru"]}`}>
              {"Elena Rojas"}
            </span>
          </div>
          <div className={` ${id} ${styles["Egj93vo"]}`}>
            <span className={` ${id} ${styles["Es5ou3n"]}`}>
              {"AI Researcher, DeepMind"}
            </span>
          </div>
        </div>
        <div className={` ${id} ${styles["E6l1g26"]}`}>
          <div className={` ${id} ${styles["Etmkw30"]}`}>
            <span className={` ${id} ${styles["E67wkbv"]}`}>
              {"UNMATCHED OPPORTUNITIES"}
            </span>
          </div>
          <div className={` ${id} ${styles["El62r5p"]}`}>
            <span className={` ${id} ${styles["Ewsihdo"]}`}>
              {
                '"From hands-on workshops to visionary talks, this summit is a must-attend for AI professionals."'
              }
            </span>
          </div>
          <div className={` ${id} ${styles["Ehqykg2"]}`} />
          <div className={` ${id} ${styles["En05myn"]}`}>
            <span className={` ${id} ${styles["Eymld6m"]}`}>
              {"David Laurent"}
            </span>
          </div>
          <div className={` ${id} ${styles["E6aiog7"]}`}>
            <span className={` ${id} ${styles["Ehwyeo6"]}`}>
              {"CEO, FutureAI Labs"}
            </span>
          </div>
        </div>
      </div>
      <div className={` ${id} ${styles["El2vzyu"]}`}>
        <div className={` ${id} ${styles["Ew8f2ag"]}`}>
          <span className={` ${id} ${styles["E7uusif"]}`}>
            {"REGISTER NOW"}
          </span>
        </div>
        <div className={` ${id} ${styles["Eaj9uyl"]}`}>
          <span className={` ${id} ${styles["Em5pl6k"]}`}>
            {
              "Secure your spot at the Next-Gen AI Summit 2052 and join the future of AI innovation."
            }
          </span>
        </div>
        <div className={` ${id} ${styles["Enivo5y"]}`}>
          {SVGs.types.landing.countdown_frame("none")}
        </div>
        <div className={` ${id} ${styles["Eb033d3"]}`}>
          <span className={` ${id} ${styles["Emmitl2"]}`}>
            {"Early Bird Pricing Ends In:"}
          </span>
        </div>
        <div className={` ${id} ${styles["Eg96pia"]}`}>
          <span className={` ${id} ${styles["Ervmfq9"]}`}>{"12:05:30"}</span>
        </div>
        <div className={` ${id} ${styles["Efmbeg9"]}`}>
          <span className={` ${id} ${styles["Er8r4o8"]}`}>{"DAYS"}</span>
        </div>
        <div className={` ${id} ${styles["Ey61g3t"]}`}>
          <span className={` ${id} ${styles["Eard4co"]}`}>{"HOURS"}</span>
        </div>
        <div className={` ${id} ${styles["Eplmhcg"]}`}>
          <span className={` ${id} ${styles["E1827kf"]}`}>{"MINUTES"}</span>
        </div>
      </div>
      <div className={` ${id} ${styles["E9lp2tc"]}`}>
        <div className={` ${id} ${styles["E00sk8c"]}`}>
          <span className={` ${id} ${styles["Ebn8agb"]}`}>
            {"Ticket Options"}
          </span>
        </div>
        <div className={` ${id} ${styles["Ey4vl39"]}`}>
          <div className={` ${id} ${styles["E87c4t9"]}`}>
            <span className={` ${id} ${styles["Ejtrv18"]}`}>
              {"EARLY BIRD PASS"}
            </span>
          </div>
          <div className={` ${id} ${styles["Evoabsj"]}`}>
            <span className={` ${id} ${styles["E7aq20i"]}`}>
              {"Limited time offer!"}
            </span>
          </div>
          <div className={` ${id} ${styles["Etmsyxd"]}`}>
            <span className={` ${id} ${styles["E684n68"]}`}>{"€299"}</span>
          </div>
          <div className={` ${id} ${styles["Esprxt6"]}`}>
            <div className={` ${id} ${styles["E3gsh0u"]}`}>
              <span className={` ${id} ${styles["Ef3878t"]}`}>
                {"Get your ticket"}
              </span>
            </div>
            <div className={` ${id} ${styles["Eo363k7"]}`}>
              {SVGs.types.landing.arrow_dark("meet")}
            </div>
          </div>
        </div>
        <div className={` ${id} ${styles["Euf2hkc"]}`}>
          <div className={` ${id} ${styles["Ew8n54t"]}`}>
            <span className={` ${id} ${styles["E7v2vcs"]}`}>
              {"STANDARD PASS"}
            </span>
          </div>
          <div className={` ${id} ${styles["Ee1j3t0"]}`}>
            <span className={` ${id} ${styles["Epnyu0z"]}`}>{"€399"}</span>
          </div>
          <div className={` ${id} ${styles["Em0x4nv"]}`}>
            <div className={` ${id} ${styles["Egp08kn"]}`}>
              <span className={` ${id} ${styles["Esbfysm"]}`}>
                {"Get your ticket"}
              </span>
            </div>
            <div className={` ${id} ${styles["Eo14ucn"]}`}>
              {SVGs.types.landing.arrow_white_ticket("meet")}
            </div>
          </div>
        </div>
        <div className={` ${id} ${styles["Em2rqwh"]}`}>
          <div className={` ${id} ${styles["Ela6183"]}`}>
            <span className={` ${id} ${styles["Ewwlrg2"]}`}>
              {"VIP EXPERIENCE"}
            </span>
          </div>
          <div className={` ${id} ${styles["E83idn2"]}`}>
            <span className={` ${id} ${styles["Ejpy3v1"]}`}>
              {"Includes exclusive speaker meetups & front-row seating"}
            </span>
          </div>
          <div className={` ${id} ${styles["Etx0n3s"]}`}>
            <span className={` ${id} ${styles["E6icbcn"]}`}>{"€699"}</span>
          </div>
          <div className={` ${id} ${styles["Etbsskl"]}`}>
            <div className={` ${id} ${styles["E9vynkm"]}`}>
              <span className={` ${id} ${styles["Eliedsl"]}`}>
                {"Get your ticket"}
              </span>
            </div>
            <div className={` ${id} ${styles["Efykaqy"]}`}>
              {SVGs.types.landing.arrow_white_ticket("meet")}
            </div>
          </div>
        </div>
      </div>
      <div className={` ${id} ${styles["Epqe2f9"]}`}>
        <div className={` ${id} ${styles["E51g7uv"]}`}>
          <span className={` ${id} ${styles["Egnvy2u"]}`}>
            {"We’re Here To Connect And Assist You"}
          </span>
        </div>
        <div className={` ${id} ${styles["Efi62gy"]}`}>
          <span className={` ${id} ${styles["Er4lsox"]}`}>
            {
              "Have questions about the summit? Need help with registration or travel? Our team is ready to assist you."
            }
          </span>
        </div>
        <div className={` ${id} ${styles["E1mbie5"]}`}>
          <span className={` ${id} ${styles["Ed8r8m4"]}`}>{"CONTACT US"}</span>
        </div>
        <div className={` ${id} ${styles["Epq16o9"]}`}>
          <span className={` ${id} ${styles["E2bcux4"]}`}>
            {"+31 20 123 4567"}
          </span>
        </div>
        <div className={` ${id} ${styles["E24clqh"]}`}>
          <span className={` ${id} ${styles["Edqsbyg"]}`}>{"EMAIL"}</span>
        </div>
        <div className={` ${id} ${styles["Es7be45"]}`}>
          <span className={` ${id} ${styles["E4sn2d0"]}`}>
            {"info@nexus.com"}
          </span>
        </div>
        <div className={` ${id} ${styles["E8m3c4f"]}`}>
          <span className={` ${id} ${styles["Ek8j2ce"]}`}>
            {"EVENT LOCATION"}
          </span>
        </div>
        <div className={` ${id} ${styles["Edevwyu"]}`}>
          <span className={` ${id} ${styles["Ep1bn6t"]}`}>
            {"Horizon Convention Center\nAmsterdam, Netherlands"}
          </span>
        </div>
        <div className={` ${id} ${styles["Ektimsz"]}`}>
          <span className={` ${id} ${styles["Ewfyd0y"]}`}>{"FOLLOW US"}</span>
        </div>
        <div className={` ${id} ${styles["Eck5ps7"]}`}>
          {SVGs.types.landing.social_icons_contact("meet")}
        </div>
        <div className={` ${id} ${styles["Euezyhp"]}`}>
          <div className={` ${id} ${styles["Ea02sbh"]}`}>
            <span className={` ${id} ${styles["Elmiijg"]}`}>
              {"GET IN TOUCH"}
            </span>
          </div>
          <div className={` ${id} ${styles["Ew924hu"]}`}>
            <span className={` ${id} ${styles["E7vhupt"]}`}>
              {
                "Reach out with inquiries about tickets, partnerships, or event details."
              }
            </span>
          </div>
          <div className={` ${id} ${styles["Emd7ie4"]}`}>
            <span className={` ${id} ${styles["Exzn8m3"]}`}>{"Name"}</span>
          </div>
          <div className={` ${id} ${styles["Efckw6r"]}`}>
            {SVGs.types.landing.line_413("none")}
          </div>
          <div className={` ${id} ${styles["E1pe1k4"]}`}>
            <span className={` ${id} ${styles["Edbtrs3"]}`}>{"Email"}</span>
          </div>
          <div className={` ${id} ${styles["E3bj1q5"]}`}>
            {SVGs.types.landing.line_413("none")}
          </div>
          <div className={` ${id} ${styles["Erwftl0"]}`}>
            <span className={` ${id} ${styles["E4hrhtv"]}`}>{"Subject"}</span>
          </div>
          <div className={` ${id} ${styles["Ewkro8y"]}`}>
            {SVGs.types.landing.line_413("none")}
          </div>
          <div className={` ${id} ${styles["Ekrbouc"]}`}>
            <span className={` ${id} ${styles["Ewdrf2b"]}`}>{"Message"}</span>
          </div>
          <div className={` ${id} ${styles["En8fcci"]}`}>
            {SVGs.types.landing.line_413("none")}
          </div>
          <div className={` ${id} ${styles["Ea0tju4"]}`}>
            <div className={` ${id} ${styles["Ebfvoan"]}`}>
              <span className={` ${id} ${styles["En2beim"]}`}>
                {"Send message"}
              </span>
            </div>
          </div>
        </div>
        <div className={` ${id} ${styles["Eu6dj3q"]}`} />
        <div className={` ${id} ${styles["Ewdrf7z"]}`}>
          {SVGs.types.landing.map_pin("meet")}
        </div>
      </div>
      <div className={` ${id} ${styles["Euq74mw"]}`}>
        <div className={` ${id} ${styles["Ei81dw5"]}`}>
          <span className={` ${id} ${styles["Etuh444"]}`}>
            {"Next-Gen AI Summit 2052"}
          </span>
        </div>
        <div className={` ${id} ${styles["Ecqwsrt"]}`}>
          <span className={` ${id} ${styles["Eodcizs"]}`}>{"Agenda"}</span>
        </div>
        <div className={` ${id} ${styles["Edvo8mr"]}`}>
          <span className={` ${id} ${styles["Epi3yuq"]}`}>{"Speakers"}</span>
        </div>
        <div className={` ${id} ${styles["Eah3cmm"]}`}>
          <span className={` ${id} ${styles["Em3j2ul"]}`}>{"Register"}</span>
        </div>
        <div className={` ${id} ${styles["Emh0et9"]}`}>
          <span className={` ${id} ${styles["Ey3g518"]}`}>{"Venue"}</span>
        </div>
        <div className={` ${id} ${styles["Eiyps4f"]}`}>
          <span className={` ${id} ${styles["Eul5ice"]}`}>{"FAQ"}</span>
        </div>
        <div className={` ${id} ${styles["E6i7hwi"]}`}>
          <span className={` ${id} ${styles["Ei4n84h"]}`}>
            {"Terms & Conditions"}
          </span>
        </div>
        <div className={` ${id} ${styles["E0z4wql"]}`}>
          <span className={` ${id} ${styles["Eclkmyk"]}`}>
            {"Privacy Policy"}
          </span>
        </div>
        <div className={` ${id} ${styles["Eooc1wr"]}`}>
          <span className={` ${id} ${styles["E0ars4q"]}`}>
            {"Cookie Policy"}
          </span>
        </div>
        <div className={` ${id} ${styles["Eiiiirc"]}`}>
          <span className={` ${id} ${styles["Eu4y8zb"]}`}>
            {"© 2052 Next-Gen AI Summit. All rights reserved."}
          </span>
        </div>
        <div className={` ${id} ${styles["Eodtrch"]}`}>
          <div className={` ${id} ${styles["E389lc9"]}`}>
            <span className={` ${id} ${styles["Eeupbk8"]}`}>
              {"STAY UPDATED"}
            </span>
          </div>
          <div className={` ${id} ${styles["Ead1ydv"]}`}>
            <span className={` ${id} ${styles["Elzholu"]}`}>
              {"Subscribe for event updates & exclusive content."}
            </span>
          </div>
          <div className={` ${id} ${styles["Ec20hk4"]}`}>
            <span className={` ${id} ${styles["Enog7s3"]}`}>{"Email"}</span>
          </div>
          <div className={` ${id} ${styles["E810g8c"]}`}>
            {SVGs.types.landing.line_462("none")}
          </div>
          <div className={` ${id} ${styles["Ef3tzhh"]}`}>
            <div className={` ${id} ${styles["Eo0comh"]}`}>
              <span className={` ${id} ${styles["Ezmseug"]}`}>
                {"Stay updated"}
              </span>
            </div>
          </div>
          <div className={` ${id} ${styles["Epq3g2l"]}`}>
            <span className={` ${id} ${styles["E2bf4bg"]}`}>{"FOLLOW US"}</span>
          </div>
          <div className={` ${id} ${styles["Eyj20cb"]}`}>
            {SVGs.types.landing.social_icons_footer("meet")}
          </div>
        </div>
      </div>
    </div>
  );
};
