// This file is generated by Misaki Studio. Do not edit.
"use client";
import * as react from "react";
import * as msi from "misaki-studio-internal";
import * as ComponentsAtomsDrawing from "../components/atoms/drawing";
import styles from "./index.module.scss";

export default ({
  className = "",
  style,
  divProps,
}: {
  className?: string;
  style?: React.CSSProperties;
  divProps?: msi.DivProps;
}) => {
  const id = msi.utils.getCount();
  const rootElement = react.useRef<HTMLDivElement>(null);
  return (
    <div
      {...divProps}
      style={{ ...style }}
      className={`${className} misaki-project-content  ${id} ${styles["Elppf60"]}`}
      ref={(element) => {
        (rootElement as any).current = element;
        divProps?.ref?.(element);
      }}
    >
      <ComponentsAtomsDrawing.Component
        className={` ${id} ${styles["Espry1j"]}`}
        divProps={{}}
      />
    </div>
  );
};
