import * as react from "react";

/**
 * GENERATED by Misaki Studio. The typed client for this project's database.
 *
 * Every call goes to the generated backend. Nothing here filters, sorts or
 * decides access — the server does all of that, because a rule applied in the
 * browser is a rule the caller can edit.
 */

/** Where the generated backend is listening. Set NEXT_PUBLIC_MISAKI_API_URL in
 * the site's environment; the default is the boilerplate's own dev port. */
export const baseUrl = () =>
  (typeof process !== "undefined" && process.env?.NEXT_PUBLIC_MISAKI_API_URL) ||
  "http://localhost:4000";

const TOKEN_KEY = "misaki.session";

/**
 * The session token.
 *
 * ⚠️ An OPAQUE HANDLE. It is meaningless on its own and is resolved by a lookup
 * on the server, so nothing here can mint one or read an identity out of one.
 * Storing it is all this file is entitled to do with it.
 */
export const getToken = (): string | undefined => {
  try {
    return window.localStorage.getItem(TOKEN_KEY) || undefined;
  } catch {
    return undefined;
  }
};

export const setToken = (token?: string) => {
  try {
    if (token) window.localStorage.setItem(TOKEN_KEY, token);
    else window.localStorage.removeItem(TOKEN_KEY);
  } catch {
    // A browser with storage blocked signs in for one page load. Signed-out is
    // a valid state, so this is a degraded session rather than an error.
  }
};

async function request(path: string, init?: RequestInit) {
  const token = getToken();
  const response = await fetch(`${baseUrl()}${path}`, {
    ...init,
    headers: {
      "content-type": "application/json",
      ...(token ? { authorization: `Bearer ${token}` } : {}),
      ...(init?.headers || {}),
    },
  });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body?.error || "request failed");
  return body;
}

export type ViewParams = { [name: string]: string | undefined };

/**
 * Run a view.
 *
 * ⚠️ Returns rows, or throws. It never returns a partial answer: an empty array
 * means the server matched nothing, which is also what a view you may not read
 * returns — those two are deliberately indistinguishable (plan §6.5).
 */
export async function query(
  name: string,
  params: ViewParams = {},
  options: { page?: number; limit?: number } = {},
): Promise<any[]> {
  const search = new URLSearchParams();
  Object.entries(params).forEach(([key, value]) => {
    if (value !== undefined) search.set(key, String(value));
  });
  if (options.page !== undefined) search.set("page", String(options.page));
  if (options.limit !== undefined) search.set("limit", String(options.limit));
  const suffix = search.toString();
  const body = await request(`/views/${encodeURIComponent(name)}${suffix ? `?${suffix}` : ""}`);
  return body?.rows || [];
}

/** Run a write action. Throws on refusal — a write that reported success and
 * did nothing is the worst available outcome (plan §4C.2). */
export async function run(
  name: string,
  input: { values?: { [name: string]: string | undefined }; params?: ViewParams; rowId?: string } = {},
): Promise<any> {
  const body = await request(`/actions/${encodeURIComponent(name)}`, {
    method: "POST",
    body: JSON.stringify(input),
  });
  return body?.result;
}

export async function signIn(email: string, password: string) {
  const body = await request("/auth/sign-in", {
    method: "POST",
    body: JSON.stringify({ email, password }),
  });
  setToken(body?.token);
  return body?.token as string | undefined;
}

/** Sign-out is DELETION on the server, and forgetting the handle here. */
export async function signOut() {
  try {
    await request("/auth/sign-out", { method: "POST" });
  } finally {
    setToken(undefined);
  }
}

/**
 * Read a view as React state.
 *
 * ⚠️ The initial value is an EMPTY ARRAY, never `undefined`. A `repeat` over
 * this renders nothing on the first paint rather than throwing, which matches
 * what preview shows for a view that has refused.
 *
 * ⚠️ The effect depends on the SERIALISED params, not on the object. A mount's
 * parameter values are expressions re-evaluated every render, so a fresh object
 * arrives each time — depending on its identity would refetch forever.
 */
export function useView(name: string, params: ViewParams = {}): any[] {
  const [rows, setRows] = react.useState<any[]>([]);
  const key = JSON.stringify(params);
  react.useEffect(() => {
    let live = true;
    query(name, JSON.parse(key))
      .then((result) => {
        if (live) setRows(result);
      })
      .catch(() => {
        // Fail CLOSED: a failed query shows nothing, never the last answer for
        // a different set of parameters.
        if (live) setRows([]);
      });
    return () => {
      live = false;
    };
  }, [name, key]);
  return rows;
}
