// This file is generated by Misaki Studio. Do not edit.
export type Config = { host: string; path: string };
export type Query = {};
export type Body = {};
export type Headers = {};
export type Response = {};
export const Check = {
  config: { host: "", path: "" },
  query: {},
  headers: {},
  body: {},
};
