// This file is generated by Misaki Studio. Do not edit.
"use client";
import * as react from "react";
import * as msi from "misaki-studio-internal";
import { SVGs } from "../../design-system/images";
import styles from "./drawing.module.scss";

export const Component = ({
  className = "",
  style,
  divProps,
}: {
  className?: string;
  style?: React.CSSProperties;
  divProps?: msi.DivProps;
}) => {
  const id = msi.utils.getCount();
  const rootElement = react.useRef<HTMLDivElement>(null);
  return (
    <div
      {...divProps}
      style={{ ...style }}
      className={`${className} misaki-project-content  ${id} ${styles["E3j8fdf"]}`}
      ref={(element) => {
        (rootElement as any).current = element;
        divProps?.ref?.(element);
      }}
    >
      <div className={` ${id} ${styles["Eckhugh"]}`}>
        <div className={` ${id} ${styles["Eh1savi"]}`}>
          <div className={` ${id} ${styles["Eci3xlx"]}`}>
            <div className={` ${id} ${styles["Eq8j6g7"]}`}>
              <div className={` ${id} ${styles["Eo237rw"]}`} />
              <div className={` ${id} ${styles["Ewjb0gk"]}`} />
              <div className={` ${id} ${styles["Eg401fy"]}`} />
              <div className={` ${id} ${styles["Enz6fnz"]}`} />
              <div className={` ${id} ${styles["Enassju"]}`} />
              <div className={` ${id} ${styles["Eavegyw"]}`} />
              <div className={` ${id} ${styles["Eyl92s6"]}`} />
              <div className={` ${id} ${styles["Eyy3nx7"]}`} />
            </div>
            <div className={` ${id} ${styles["Enetn98"]}`}></div>
            <div className={` ${id} ${styles["Eltew4z"]}`}>
              <msi.shader.Shader
                {...{
                  noise: 0.25,
                  shape: "blob",
                  speed: 1,
                  type_: "grain-gradient",
                  colors: ["#FF3F8F", "#0386C8"],
                  softness: 0.5,
                  colorBack: "#FFFFFF",
                  intensity: 0.5,
                }}
                style={{ width: "100%", height: "100%" }}
              />
            </div>
          </div>
        </div>
        <div className={` ${id} ${styles["Ekqbym8"]}`} />
        <div className={` ${id} ${styles["E66j00h"]}`} />
      </div>
      <div className={` ${id} ${styles["Eb7dn7j"]}`}>
        <div className={` ${id} ${styles["Etzpxgk"]}`}>
          <div className={` ${id} ${styles["E7jwkg7"]}`}>
            {SVGs.types.featureCardIcons.drawing("meet")}
          </div>
        </div>
        <div className={` ${id} ${styles["En1c6y5"]}`}>
          <span className={` ${id} ${styles["E76ur2o"]}`}>{"Drawing"}</span>
        </div>
        <div className={` ${id} ${styles["Eeffu1u"]}`}>
          <span className={` ${id} ${styles["E6wfqxl"]}`}>
            {
              "Draw paths, shapes and meshes on the canvas. Every point stays editable."
            }
          </span>
        </div>
      </div>
    </div>
  );
};
