// This file is generated by Misaki Studio. Do not edit.
import styles from "./sample.module.scss";
export const Component = () => {
  return (
    <article className={[styles.document, "misaki-document"].join(" ")}>
      <p className={"paragraph"} />
    </article>
  );
};
