// This file is generated by Misaki Studio. Do not edit.

/**
 * One row of database/auth/roles, as the exported views return it.
 *
 * `id` is the row's own id and is always present. Every column is OPTIONAL:
 * a cell that was never filled in has no value at all, and a view may
 * project only some columns, so nothing here can be promised.
 *
 * Secret columns are absent by construction — the evaluator drops them
 * from the model before it projects anything.
 */
export type RolesRow = {
  id: string;
};

/**
 * The rows the PUBLIC views of this table return.
 *
 * ⚠️ A RESTRICTED view's rows are NOT here, and that is deliberate:
 * anything in this bundle has already reached the browser, so shipping
 * them and hiding them would be a leak with extra steps. They are served
 * by the generated backend instead.
 */
const rows: RolesRow[] = [];
