// This file is generated by Misaki Studio. Do not edit.

/**
 * database/auth/users is deliberately NOT exported.
 *
 * It holds password hashes, and a bundle is a file anyone can read.
 * Its rows, its views and even its row TYPE are absent — the
 * generated backend serves them, where a session can be verified.
 */
export {};
